[package]
name = "minitools"
version = "0.1.0"
authors = ["Sebastian Morr <sebastian@morr.cc>"]
edition = "2018"

[dependencies]
byteorder = "1"
rustyline = "6"
tempfile = "3"

[lib]
name = "minitools"
path = "src/lib.rs"
